### PR TITLE
Fix HTML validation errors

### PR DESCRIPTION
**Pull request by niqjohnson**
Fixes a few HTML validation errors that might cause accessibility problems (per GHE issue 189)

## Additions

- Empty `alt` attributes to all the lifestyle illustrations (those kinds of illustrations are often coded as background images elsewhere on the site, so having an empty `alt` for all of those seems like the right way to go)
- An ID to the salary tooltip content to associate it with the tooltip trigger via `aria-describedby`

## Removals

- Empty `maxlength` attribute from the salary input (`maxlength` can't be empty)
- Old, unneeded test

## Changes

- Move a couple of block-level elements out of places where block-level elements aren't allowed

## Testing

- Everything in this branch should look and work exactly as it does on build in all browsers, at all screen sizes, and in both languages.
- Running the page through https://validator.w3.org/ should give the screenshot below (i.e. only errors in the header and on non-standard input attributes, which I've filtered out in the screenshot).

## Review

- @marteki 
- @higs4281 

## Screenshots

validator

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by mistergone** [comment]
:+1:

Hooray for validation!

**Comment by niqjohnson** [comment]
Fixed a few merge conflicts. @mistergone or @marteki or @higs4281, anyone want to test again, or should I go ahead and finally merge this one?

**Comment by higs4281** [comment]
I pulled into my standalone branch and it looks great. i'd vote for merge 💯

**Comment by marteki** [comment]
:+1:

**Pull request merged**
