### PR TITLE
adjust graph text when consumer is 70 (per issue #118)

### PR DESCRIPTION
**Pull request by higs4281**
Short description explaining the high-level reason for the pull request

## Additions

- add conditional to handle consumers who are 70 years old

## Testing

- if testing in UnityBox, be sure to run `python manage.py collectstatic` before checking

## Review

- @niqjohnson @marteki 

## Screenshots
age70

## Checklist
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Passes all existing automated tests
* [x] Visually tested

### CODE REVIEW

**Comment by marteki** [comment]
:+1: Reviewed. Approved as looking and working great.

**Comment by niqjohnson** [comment]
Working for me. Question, though: do we need the `else` in there? Now that we're showing an error message if the user is older than 70, is there a way for anyone to get the "is past your full benefit claiming age" text?

**Comment by higs4281** [comment]
@niqjohnson the else (at line 398) isn't for older-than-70 folks, but for past-fra people younger than 70.

we first catch 70-year-olds, then handle younger past-fras.

**Comment by niqjohnson** [comment]
Ah, of course! I was totally reading that backwards. Looks good to me :+1:

**Pull request merged**
