### PR TITLE
Add linting to grunt tasks

### PR DESCRIPTION
**Pull request by mistergone**
Added [linting](https://en.wikipedia.org/wiki/Lint_%28software%29) to grunt tasks and added `gruntify-eslint` to our npm packages.

## Additions
- added `gruntify-eslint` to `package.json`
- added `grunt lint` task that runs lint task
- added a `conf` directory for configurations, and added `eslint.yaml` (which is a slight edit of our front-end standards `.eslintrc` file)

## Review

- @marteki, @higs4281, @niqjohnson - pull this in and try it, please, and try not to be horrified by the results of the linting. :grin: 

## Checklist
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by niqjohnson** [comment]
:+1:

**Comment by marteki** [comment]
:open_mouth: 
:smile:
:+1:

**Comment by higs4281** [comment]
:+1: works for me, and looks just like my jslint sessions!

**Comment by mistergone** [comment]
I forgot that we merge our own PRs now. Oops! :red_circle: :octopus:

**Pull request merged**
