### PR TITLE
Documentation and clean-up

### PR DESCRIPTION
**Pull request by mistergone**
This PR adds JSDoc documentation to much of the code and cleans up many warnings and errors from the linter (but not all of them!).

Short description explaining the high-level reason for the pull request

## Additions
- JSDoc comments for many functions

## Removals
- Removed `calculate-age.js` because the function is no longer used or needed.

## Changes
- Numerous changes around spacing, quotes around object properties, length of lines, and similar issues.
- __Note: __ There are no "functional" changes in this PR. That is, the code should work exactly the same as before.

## Testing
- Pull it down and make sure it does what it did before...

## Review
- @marteki @niqjohnson @higs4281 

## Todos
- More cleanup remains

## Checklist
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices 
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

## Animated GIF
minion-cleanup

### CODE REVIEW

**Comment by higs4281** [comment]
👍 nice; can find no functional changes.

**Comment by niqjohnson** [comment]
👍 

Everything was working for me in standalone just as it was before.

Also, `gulp lint` is down from 45 errors and 232 warnings to 15 errors and 145 warnings. Nice progress!

**Comment by marteki** [comment]
And a third :+1:, as it's still working as it was before in standalone for me.

Yay! :tada:

**Comment by mistergone** [comment]
This looks sooooooo merge-able. Here it goes!

**Pull request merged**
