### PR TITLE
Retirement age selector fix

### PR DESCRIPTION
**Pull request by mistergone**
I added a function to `questions-view.js` for Step 3's retirement age selector ("#retirement-age-selector"). When Step 2's questions are updated based on user age, this function removes any options from the SELECT that are less than the user's current age.

In other words, a user who is 65 will not be asked if they are considering retiring at 62.

## Additions
- `limitAgeSelector` in `questions-view.js`

## Testing
- Pull it down, open up the old browser, put in some ages greater than 62, and see what happens in Step 3's age selector!

## Review
- @marteki and @niqjohnson and @higs4281 

## Screenshots
screen shot 2016-05-03 at 11 13 49 am

## Checklist
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices 
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

## Animated GIF
Writing real code after writing documentation and fixing linting errors for a week has me all like:
i-was-alive

### CODE REVIEW

**Comment by higs4281** [comment]
👍 tested birth years from 1945 to 1954, and all work as expected.

**Comment by marteki** [comment]
:+1: all working as expected! Now with bonus `select-fix` from Nicholas.

**Comment by niqjohnson** [comment]
Looking good for me in Chrome, but hiding the options with CSS didn't remove them from the select for me in these OS/browsers:

- Mac/Safari
- Win7/IE 11 (Sauce Labs)
- Win7/IE 10 (Sauce Labs)
- Win7/IE 9 (Sauce Labs)
- Win7/IE 8 (Sauce Labs)
- Android 4.4 emulator (Sauce Labs)
- iOS 9.2 emulator (Sauce Labs)

**Comment by mistergone** [comment]
Thank you for that, @niqjohnson ! I didn't expect that at all. I'll find a fix.

**Comment by mistergone** [comment]
Now tested in:

* Mac/Safari
* Win7/IE 11 (Sauce Labs)
* Win7/IE 10 (Sauce Labs)
* Win7/IE 9 (Sauce Labs)
* Win7/IE 8 (Sauce Labs)
* Android 4.4 emulator (Sauce Labs)
* iOS 9.2 emulator (Sauce Labs)

And working!

**Comment by niqjohnson** [comment]
👍 

Working for me in all the browsers I tried. Nice!

**Comment by marteki** [comment]
Tested on:

* Mac/Chrome
* Mac/Safari
* iOS 9.2 emulator (Sauce Labs)
* iOS 8.0 emulator (Sauce Labs)
* Android 4.4 emulator (Sauce Labs)
* Windows 10/Edge (Sauce Labs)
* Windows 8.1/IE 11 (Sauce Labs)
* Windows 7/IE 10 (Sauce Labs)
* Windows 7/IE 9 (Sauce Labs)
* Windows 7/IE 8 (Sauce Labs)

All working properly. :+1:

**Comment by mistergone** [comment]
Thanks for double-checking this, everyone! I'll merge once the checks complete.

**Pull request merged**
