### PR TITLE
Add lifestyle question graphics with Spanish text

### PR DESCRIPTION
**Pull request by marteki**
We have graphics that have English text in them. On the Spanish implementation, they should swap to images with Spanish text.

lifestyle-working switches to (updated image) sus60s

and

lifestyle-expenses switches to (updated image) gastos

## Additions

- added images with Spanish text to images directory
- added CSS to trigger the switch based on the data-lang attribute

(There were issues with the standalone app working as well. @higs4281 and I worked together to get the needed URL redirects reinstated, and I pulled in stuff from his `spanish` branch to get it going.)

Also, Bill Higgins and I discovered that the spinner is no longer stopping for any browser, anywhere. A possible fix for that is incoming.

## Removals

- None

## Changes

- Items were changed on the `spanish` branch that I referenced above.

## Testing

- Tested on OS X Chrome. **Needs testing on all the other browsers**, but I don't have access to any others right now. 

## Review

- @mistergone @niqjohnson @higs4281 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices 
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by caheberer** [comment]
The images look blurry...I assume that's just a github issue?

**Comment by marteki** [comment]
Might be a me issue. :-( Let me check later this morning...

**Comment by marteki** [comment]
Double check:

sus60s

gastos

**Comment by caheberer** [comment]
I think it's just github, it's increasing the size here. If I drag off and open they are fine, so it should be okay.

**Comment by higs4281** [comment]
es icon swap not working for me in unitybox.

**Comment by marteki** [comment]
@higs4281 Oof! And I just checked more browsers on my personal devices.

Working in: Chrome, Safari, Mobile Chrome Beta
Not working: Firefox.

Okay, that gives me direction.

**Comment by marteki** [comment]
Hey, @higs4281 - I think I cracked the code. Could you try it in Unitybox now?

**Comment by higs4281** [comment]
works! :+1:

**Comment by marteki** [comment]
And it's working in Firefox, Chrome, Safari, and Mobile Chrome. Reportedly in IE and iOS Safari as well, according to the internet.

I'll fix  the merge conflicts, then send it off.

**Pull request merged**
