### PR TITLE
Fix for lifetime benefits

### PR DESCRIPTION
**Pull request by mistergone**
This PR fixes the lifetime benefits number when the user's age is greater than 62.

## Additions
- Code to fix lifetime benefits

## Review

- @marteki @higs4281 @niqjohnson 

## Checklist
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices 
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by imuchnik** [comment]
@mistergone this commit is failing tests on Travis with an AssertionError, so probably something to look into. Also, good time to add a corresponding test to verify this change as well. :smile:

**Comment by mistergone** [comment]
@imuchnik - I'm working with @higs4281 on the Travis error. I'm also working on overhauling this repo so that we can achieve a __lot__ more test coverage.

**Comment by niqjohnson** [comment]
Travis errors aside, this passes the suggested test case from GHE issue 169: someone born on 9-15-1952 with an income of $60,000 and claiming at age 63 should have a lifetime benefit of $334,626, not $342,408. So, the calculation itself looks good to me.

**Comment by marteki** [comment]
Thanks for the Travis text fix, Chuck! This addresses the edge case in the GHE issue for me as well. :+1:

**Comment by mistergone** [comment]
Merging this.

**Comment by imuchnik** [comment]
@mistergone That is great news, though I am weary of big, all-at-once overhauls. Small incremental improvements seem to produce better long term results. This file is already included in the test file, so a quick test is pretty easy. In general, adding a test for each bug fixed is a good practice and helps to maintain the coverage.

**Pull request merged**
