### PR TITLE
App rebuilt to use gulp, properly use capital-framework, conform to CommonJS

### PR DESCRIPTION
**Pull request by mistergone**
This PR swaps from `grunt` to `gulp`, includes `capital-framework` properly, and begins to modularize the JS scripts (changing them to CommonJS formatting and using `browserify` to compile them). It also does the same for our CSS files.

## Additions
- `gulp` and associated packages
- `bower` (for `capital-framework 1.0.0`)

## Removals
- `grunt` and associated packages

## Changes
- CSS source (now `claiming.less`) was moved to `src/css/` directory, and is now compiled and placed in `retirement_api/static/retirement/css/`
- JS was split into multiple files where possible and `gulp` will now `browserify` the files into `main.js` in `retirement_api/static/retirement/js/`
- `raphael-min.js` is now in `src/js/raphael-lib` and is copied by gulp into `retirement_api/static/retirement/js/` 
- Changed `base.html` and `standalone_base.html` to use new compiled CSS and JS files.
- updated `frontendbuild.sh`

## Testing
- Pull it down, and run `frontendbuild.sh` (which will run `bower install` and `npm install` and `gulp`)
- `gulp watch` works, too (but run `frontendbuild.sh` first)

## Review
- @marteki @niqjohnson @higs4281 

## Todos
- Clean up `claiming.less` so that it's actually a LESS file and not just a CSS file that I renamed
- Split JS into model and view

## Checklist
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices 
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

## Animated GIF

Uh... there, I fixed it?

fixed-it

### CODE REVIEW

**Comment by mistergone** [comment]
Slight update - I changed `frontendbuild.sh` so that it will run all you need for the front-end.

**Comment by marteki** [comment]
Woot, woot, woot! :+1: all over the place! Which is to say, means that it works for me on standalone. :smile: 

Can't wait to get both the common nav menu and CF 3+ in here, now that we can easily.

**Comment by higs4281** [comment]
:+1: monumental! tested on UnityBox.

**Comment by niqjohnson** [comment]
:+1:

Niiiiiice!

**Comment by mistergone** [comment]
Merging!

merge

**Pull request merged**
