### PR TITLE
Change button text to the standard typeface

### PR DESCRIPTION
**Pull request by niqjohnson**
Buttons on the page had been set to Avenir Next Regular; they should be Avenir Next Medium.

## Removals

- Custom button styles (the buttons on the page will now inherit the standard Capital Framework styles, as they should)

## Testing

Buttons on the page should have these font styles:

```
font-family: AvenirNextLTW01-Medium, Arial, sans-serif;
font-style: normal;
font-variant: normal;
font-weight: 500;
```

Depending on whether you review in standalone or UnityBox, the buttons will have a `font-size` of either 14px or 16px (see note below).

## Review

- @marteki 
- @mistergone 

[Preview this PR without the whitespace changes](?w=0)

## Screenshots

buttons
(On standalone, buttons will be 16px Avenir Next Medium)

## Notes

- Per the [Design Manual](http://cfpb.github.io/design-manual/ui-toolkit/buttons.html), buttons should have a `font-size` of 16px. There's currently an error in production that's setting button text on all pages at 14px. Because we haven't updated standalone to match production yet, button text will appear at 16px if you review in standalone. If you've got a working V1 UnityBox, button text will probably appear at 14px (as it will once this change makes it to build).

## Todos

- Fix the global error that's setting button text to 14px instead of 16px

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
👍 working in standalone and looks good in comparison to production.

**Comment by marteki** [comment]
:+1: as well. Thanks, Niq!

**Comment by niqjohnson** [comment]
@higs4281: Any idea what's going on with Travis after I merged master to fix the conflicts? Is it easiest if I just cancel this PR and redo the changes in a new branch from the current master?

**Comment by mistergone** [comment]
👍

**Pull request merged**
