### PR TITLE
Update hero image and spacing

### PR DESCRIPTION
**Pull request by marteki**
Updates the hero to our new illustration, and makes adjustments to more closely align with upcoming design standards.

## Additions

- Added column classes to hero H1 and P

## Removals

- Removal of repetitive CSS code

## Changes

- Changed the background hero image to the newest illustration
- Changed the media queries to fit the changed image and the column classes for the text

## Testing

- Visually tested in Chrome, Safari, IE, and on Android Chrome.
* Still needed: visual testing on iOS Safari.

## Review

- @caheberer @niqjohnson @wernerc 

#### Over 1190px:
screen shot 2015-08-11 at 2 31 19 pm

#### Between 915px and 1189px:
screen shot 2015-08-11 at 2 33 11 pm

#### Between 850px and 914px:
screen shot 2015-08-11 at 2 34 05 pm

#### Under 850px:
screen shot 2015-08-11 at 2 34 26 pm

screen shot 2015-08-11 at 2 34 44 pm

## Checklist

* [x]  Changes are limited to a single goal (no scope creep)
* [x]  Code can be automatically merged (no conflicts)
* [x]  Passes all existing automated tests
* [x]  Visually tested

### CODE REVIEW

**Comment by niqjohnson** [comment]
Looking good. A couple of things I noticed:

- The first breakpoint happens at 1100 instead of 1189 as shown in the screenshot. Not sure if that was intentional or not.
- This is happening with the current hero, too, but I just now noticed it: the hero has less left and right padding than the rest of the page content at all but the largest screen size. Was that intended?

**Comment by marteki** [comment]
1) The breakpoint at 1100 is intentional, and the screenshot is mislabeled. :scream: Sorry about the confusion.

2) Great catch! This was noticed by @caheberer and I at some point weeks ago, and I thought we fixed it. Maybe not?

Candice, I forget what you said when we discussed this before: should the hero at non-max sizes have the wider left/right padding, or should the page content have the narrower left/right padding? (Apologies if it's clearly defined somewhere, and I could just look it up myself...)

**Comment by caheberer** [comment]
@marteki I think this is when we were looking to the new grid issue on github for clarification, but there was the open question left for Scott, which I see is still open and unclear on the total padding for small size views.

**Comment by mistergone** [comment]
You meant me, @mistergone, not @wernerc (who was also me, but I never used that account so I deleted him).

**Comment by marteki** [comment]
Oops! Sorry, Mr. @mistergone. 

I updated the side margins to be consistent. On medium and small screens, it should be showing as 30px total with 15px on each side.

**Comment by marteki** [comment]
And based on further guidance by @Scotchester, tweaked the margins again.

15px each side only for 480px screen widths and below, 30px on each side every other screen width.

**Comment by niqjohnson** [comment]
Padding is looking good now.

@mistergone: Now that the page is using different outside paddings at different screen sizes, tooltips near the very edges of the screen are a little off:

tooltip

I think that's coming from my using a constant padding of 20px in `toolTipper()`. Is the best way to fix this to change that variable to use `$('#maincontent').css('padding-left')`? Is there a better way? Should that change be part of this PR or a separate issue?

**Comment by niqjohnson** [comment]
Just noticed a little hero overflow happening on small screens:

overflow

Causes a little horizontal scroll on my iPhone 6.

**Comment by marteki** [comment]
Pushed a fix for the overflow. (The logo is oddly clipped on the right side when viewed on a simulated iPhone 4 screen in Chrome's device emulator, but the same thing is happened in production on Owning a Home. :unamused: )

**Comment by niqjohnson** [comment]
Overflow looks fixed to me on my iPhone and in Chrome's device emulator, too.

**Comment by marteki** [comment]
Shipping it! @mistergone can answer and address the tooltip question in another PR?

**Pull request merged**
