### PR TITLE
Step 2 of Grunt Adoption

### PR DESCRIPTION
**Pull request by mistergone**
Look at all this grunt integration! Wowza! :telephone_receiver: :police_car: :fire_engine: 

__Important note:__ The major change here is that we no longer have a `claiming-social-security.js` file in the repo. All edits to the JS are now done in the `src/` folder of the repo. The `claiming-social-security.js` file is generated by the `grunt build` task (which is executed when `grunt` or `grunt watch` is run).

## Additions
- `grunt-contrib-watch` added
- `grunt build` task added
- `grunt watch` task added
- `README.md` updated with front-end build instructions
- previous changes to `claiming-social-security.js` were added to `claiming-graph.js`

## Removals
- `claiming-social-security.js` has been removed from the repo and added to `.gitignore`.

## Review
- @marteki or @niqjohnson or @higs4281, please check this out and make sure it works for you!

### CODE REVIEW

**Comment by higs4281** [comment]
should raphael-min.js be included the grunt build?

**Comment by higs4281** [comment]
this works for me locally; js file gets built and site works.

a README update should be part of this change, and our documentation for release management.

**Comment by mistergone** [comment]
@higs4281 Once I add an minifying task to the grunt, Raphael (and possibly jQuery) will become a part of a single, unified JS file. But at this point, it's not strictly necessary.

**Comment by mistergone** [comment]
I'd still like 1 of [ @niqjohnson , @marteki ] to verify it works for them, and then I shall merge!

**Comment by niqjohnson** [comment]
:+1: 

I did `npm install` followed by a `grunt build` followed by a `grunt watch`. Edited the JS files in `src` and the grunt build happened. Nice!

**Comment by mistergone** [comment]
Great! I'm calling this one.

**Pull request merged**
