### PR TITLE
Welcome to npm test!

### PR DESCRIPTION
**Pull request by mistergone**
`npm test` command now works! We're testing using mocha and chai. Righteous!

Short description explaining the high-level reason for the pull request

## Additions
- `npm test` command now functional
- Many spacing fixes
- `test.js` in the `/test` directory contains JS tests

## Testing
- Added tests for 4 functions. Not impressive, but it's a start!

## Review
- @niqjohnson, @marteki - Please pull and review. (Also run `npm test`).

## Screenshots
screen shot 2015-08-13 at 3 38 23 pm

## Todos
- More tests

## Checklist
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Visually tested in supported browsers and devices 
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by niqjohnson** [comment]
:+1:

`npm test` works for me, and the page is working as expected.

Should we add a note about running `npm test` to the "How to run software tests" section of the readme?

**Comment by marteki** [comment]
Also working for me! :+1:

**Comment by ascott1** [comment]
@mistergone if you want to get super fancy, you can wire the tests into Grunt so that every JS change runs a test!

**Comment by mistergone** [comment]
@ascott1 Oh, I plan to get ___super fancy___. You already know. :dancer: :octopus:

**Comment by mistergone** [comment]
Time to merge!

**Pull request merged**
