### PR TITLE
Improve "Step 3: Learn your next steps" content and interactions

### PR DESCRIPTION
**Pull request by marteki**
This PR adds copy specifically for those who choose a planned claiming age of 70.

It also refactors the Step 3 Javascript into its own view, and hides the Step 3 content if a person deselects any ages.

## Additions

- Add specific content and JS for those who choose to claim at 70

## Changes

- Pull Step 3 Javascript out of `graph-view` and `questions-view` into its own view
- Hide Step 3 content if a person deselects any ages
- Move `isElementInView` function into its own utility

## Testing

- Pull in this branch. `gulp`, and then `./manage.py runserver`.
- I tested this in both Mac/Chrome and Win7/IE8.

## Review

- @mistergone @niqjohnson @higs4281 @amymok 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by marteki** [comment]
Just looked at this on /es/. 😭 

@higs4281, can you push the updated translations to this branch?

**Comment by higs4281** [comment]
i pushed it as the `choose-70-content` branch. i can merge it here.

**Comment by mistergone** [comment]
This looks good. I only tested a little, but I like the new view and refactoring `isElementInView()` into its own utility file. 👍

**Comment by niqjohnson** [comment]
All the content's looking good, but the "Yes/No" buttons at the end of the page weren't working for me in either English or Spanish.

**Comment by marteki** [comment]
Good catch! I think I know where to fix that. Stand by.

**Comment by marteki** [comment]
How does it look now, @niqjohnson?

**Comment by niqjohnson** [comment]
👍 

Buttons are working for me now, and English and Spanish content are looking good. Nice!

**Comment by marteki** [comment]
Ahoy! Merge ahead.

**Pull request merged**
