### PR TITLE
Updates to latest Capital Framework | Remove bower

### PR DESCRIPTION
**Pull request by anselmbradford**
## Additions

- Adds task to copy icons to static directory.

## Removals

- Removes bower.
- Removes cf enhancements that aren't referenced in the markup.

## Changes

- Updates to Capital Framework 7.x from 1.x.

## Testing

1. Turn on font cdn by setting `@use-font-cdn: true;` on line 29 of `main.less`.
2. Run `gulp build`
3. Run `python manage.py runserver`
4. Visit http://localhost:8000/before-you-claim/ and compare to https://www.consumerfinance.gov/consumer-tools/retirement/before-you-claim/
  - Enter 1900 for year born to show notification.
5. `npm test` should pass.

## Notes

- `tox` does not pass, but it does not pass on master branch either, so I'm not sure of the issue. I have not touched it, including not updating the icon syntax in the fixtures.

### CODE REVIEW

**Comment by chosak** [comment]
Thank you for taking on this upgrade! These changes work well for me, both in standalone and as part of cfgov-refresh.

I do get the following error when running `gulp` or `gulp lint`:

```sh
/Projects/retirement/gulp/tasks/copy.js
   6:32  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  13:32  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  20:32  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  27:35  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style

/Projects/retirement/gulp/utils/handle-errors.js
  20:5  warning  Don't use process.exit(); throw an error instead  no-process-exit

✖ 5 problems (4 errors, 1 warning)
  4 errors and 0 warnings potentially fixable with the `--fix` option.
```

Unfortunately, this doesn't fail the `gulp` task as one might expect/hope -- it still exits with a 0 status code.

**Comment by chosak** [comment]
> tox does not pass, but it does not pass on master branch either

@anselmbradford tox passes for me both on master and on this branch. Would you mind sharing the error message(s) that you get?

**Comment by anselmbradford** [comment]
@chosak fixed the linter errors!

**Comment by chosak** [comment]
1. Is this update intended to make any visual changes to the rendered page? If I compare [the live Before you Claim page](https://www.consumerfinance.gov/consumer-tools/retirement/before-you-claim/) with [a local one from this branch](http://localhost:8000/consumer-tools/retirement/before-you-claim/), I see a visual difference due to the change from the blue minicon to the black SVG:

    Live | Local
    ---- | -----
    image | image

2. When running in cfgov-refresh locally, this page seems to pull from the CDN even if I haven't made the code change you mention:

    image

    Other local pages use my local fonts installed [as documented here](https://cfpb.github.io/cfgov-refresh/installation/#webfonts).

**Comment by anselmbradford** [comment]
@chosak Nice catch. I pushed up a fix for the breadcrumb arrow color. The change in shape is fine, that happened in the SVG change and is reflected elsewhere on the live site.

For the cdn font, I'm forgetting how retirement is getting its header, but is it possible it's the on-demand header, which has the cdn setting on true https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/css/on-demand/header.less#L31 ?
I'm not sure it's worth digging into that too far, since it's more concerning if the fonts are NOT loading.

**Comment by chosak** [comment]
With the fix in #234, tests pass again on this branch. @anselmbradford I suspect what you write above about the CDN header is correct, although I don't fully understand how the on-demand header works.

**Pull request merged**
