### PR TITLE
Revised graph fixes (plus a small header change)

### PR DESCRIPTION
**Pull request by marteki**
* MERGE FROM BASE PROPERLY BEFORE SUBMITTING A PR, MARTEKI
* Add line "Your estimated benefits: Select claiming ages on the graph
to see your benefit increase or decrease."
* Move "View as: Monthly income / annual income" radio buttons to top
of graph
* Adjustments to previous two bullet points for spacing, padding, and alignment on medium and small screens
* Properly align the y-axis label  with the bottom of the graph
* Fixed placement of text below the graph on screens < 850
* Fixed placement of the ages, bars, and the slider path on screens <
850
* Avoid "claim-planning" at all screen sizes (now that it's been pointed out, I can't unsee the compund word)

### CODE REVIEW

**Comment by niqjohnson** [comment]
Looking good for me in Chrome, Safari, and Mobile Safari. Three small things I saw:

- The bottom of the slider is a little clipped on my iPhone 6 clipped-slider

- The comp shows the text under the slider changing from "Slide to see your estimated benefits at each claiming age." to just "Claiming age" but I'm still seeing the old text.

- The previous label text was inside of `{% trans %}` markup, but the new text isn't. Not sure if that actually has any impact on the app now. @higs4281?

**Comment by marteki** [comment]
Thanks for looking at this, Niq!

* @wernerc, I'm going to need your help on fixing the clipped slider. I think it's resulting because of the overall size that Raphael is sending through, and I'm not comfortable messing with too much of that code. I can also see that you commented out a line allowing the graph to overflow, and i don't want to tweak that if it's going to break something else.
* @caheberer, is the change back away from explicit slider instruction intentional? If so, I can change it, but I'm not sure how it'd make it more understandable that the slider is slidable.
* @higs4281, I took out the {% trans %} because several months ago, you told me to do so if I was including text that didn't have an accurate Spanish translation in the app. Is that still what i should do? If not, I can add the tags back easily... as well as all the other tags I've removed since April.

**Comment by higs4281** [comment]
no biggie either way, but i'd default to leaving the trans tags in place unless they're making things impossible. they do no harm, and set up the translations to work as they are added. much nicer for the translators when the time comes.

**Comment by marteki** [comment]
Trans tags back in. Only place I didn't add them was the menu or footer.

**Comment by mistergone** [comment]
Hrm. I actually think the best fix might be to slightly increase the height of the overall graph on mobile. Turning overflow back on miiiiight fix it and not mess anything else up. It's also worth a try.

**Comment by higs4281** [comment]
looks great! :+1:

**Pull request merged**
