### PR TITLE
fix title to avoid using nonstandard pipe (English and Spanish)

### PR DESCRIPTION
**Pull request by higs4281**
This is needed to fix browser tests that check our page title

## Additions

- use of > instead of | in title to match site standard (and avoid behave bug in browser tests) 
- also fixes mixed title translation, as noted in #118  by @OrlandoSoto 

## Review

- @marteki 
- @mistergone

### CODE REVIEW

**Comment by marteki** [comment]
When I run it from scratch on localhost (after a grunt build), I still get the pipe in the title.

screen shot 2015-11-12 at 4 06 21 pm

Also, looking at the rate checker's example, it should probably be "Planning for Retirement: Before you claim > Consumer Financial Protection Bureau".

**Comment by higs4281** [comment]
Ah, the dreaded standalone base strikes again (for the pipe appearing locally)
i'll have to redo the translations and the browser tests to handle the longer title.

**Comment by higs4281** [comment]
what if we consider the first part of the h1 as a preamble (analogous to the /retirement/ url breadcrumb)? 
then the title still matches the url and we don't have to chase this thing around all the repos?

**Comment by marteki** [comment]
If we leave off the "planning for retirement" part, then it:

* doesn't match the schema used by the rest of our tools, and
* doesn't match how the Bureau is actually referring to the tool (re calling this tool specifically "Planning for Retirement" until another tool is released).

**Comment by higs4281** [comment]
our nav 'schema' isn't that monolithic:

witness:
Economically Vulnerable Consumers (nav) > empowerment (url) > Office of Financial Empowerment (title) 

I also think our url and title better fit the future of the retirement suite of tools. 
When the day comes for a retirement landing page, "Planning for Retirement" would be the natural umbrella title.

Then downstream would be:

/retirement/before-you-claim
/retirement/investment_tools
/retirement/guide-for-couples
/retirement/whatever

**Comment by marteki** [comment]
I don't want to hold this up and keep the "&gt;" out of the pipeline. We can always change it later if needed (and our full website redesign probably will).

**Comment by higs4281** [comment]
agreed; there's a good chance we'll be redoing it either way.

**Comment by marteki** [comment]
WFM on the standalone now. Danke!

**Pull request merged**
