### PR TITLE
add tooltip content to sixties question per issue #117

### PR DESCRIPTION
**Pull request by higs4281**
Adds tooltips in the "working in your 60s" question to explain effect of claiming early and working

## Additions
- adds new tooltip in database
- adds references to the tooltip in the 'sixties' question's answers
- adds a tooltip content div to the main template

## Testing

- to test, be sure to pull in new content with `python manage.py loaddata retiredata.json`

## Review

- @marteki @niqjohnson 

## Screenshot
sixties_tooltip

## Todos

- update content on build after PR is merged and deployed

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Passes all existing automated tests
* [x] Visually tested 
* [x] Project documentation has been updated (including the 'Unreleased' section of the CHANGELOG)

### CODE REVIEW

**Comment by niqjohnson** [comment]
Working for me.

Is there a standard on whether tooltips come before or after punctuation? Looks like the tooltips in other lifestyle questions are before punctuation, but I could see that looking weird here because of the exclamation mark (like we're REALLY EXCITED about this particular tooltip).

**Comment by higs4281** [comment]
good point. it looks weird to me either way, but weirder if it intrudes before the exclamation mark.

**Comment by marteki** [comment]
:+1: Working for me.

As to the standard about how inline tooltips work with punctuation, I think we'll be defining that as part of our team's other work. Maybe it's what we look at after tables?

**Comment by niqjohnson** [comment]
:+1: Let's leave the tooltip after the punctuation since that's where it was in Serena's copy.

**Pull request merged**
