### PR TITLE
fix base so standalone app works again

### PR DESCRIPTION
**Pull request by higs4281**

### CODE REVIEW

**Comment by niqjohnson** [comment]
I think the path in line 175 isn't quite right (I'm getting a 404 for nemo.js)? Instead of:

```html
<script src="{% static "retirement/static/js/nemo.js" %}"></script>
```

I think it should be:

```html
<script src="{% static "retirement/js/nemo.js" %}"></script>
```

**Comment by higs4281** [comment]
great catch, niq. fixed.

**Comment by niqjohnson** [comment]
:+1: All the static resources are loading correctly for me now.

**Comment by marteki** [comment]
:+1:  Also working for me. Ship it!

**Pull request merged**
