### PR TITLE
Django 18

### PR DESCRIPTION
**Pull request by rosskarchner**
Fixes to support django 1.8 and wheel distribution

### CODE REVIEW

**Comment by higs4281** [comment]
@rosskarchner  What about migrations?

**Comment by rosskarchner** [comment]
from what I can tell, south migrations continue to work-- thought we should probably flatten and switch to Django migrations soon

**Comment by higs4281** [comment]
When I tried to start with 1.8 for paying-for-college, migrations and 1.8's security middleware weren't compatible, but that was 1.8 to 1.6 compatibility, not the other way. so it may be easier than I'm thinking.

The 1.8 migrations had a slightly different form that confused South in 1.6, and these middleware entries caused problems:

- django.contrib.auth.middleware.SessionAuthenticationMiddleware
- django.middleware.security.SecurityMiddleware

**Comment by rosskarchner** [comment]
Do you foresee making any database changes in the next few weeks? Once we're on 1.8, let's flatten these migrations and switch to Django native

**Comment by higs4281** [comment]
No foreseeable db changes as long as the calibration table is there (that's
what the migration created).

**Pull request merged**
