### PR TITLE
Remove unused translation entry for "Search"

### PR DESCRIPTION
**Pull request by chosak**
The Django translations file for this package includes one for the English word "Search", translated to the Spanish word "búsqueda". This translation is unused in this package, and conflicts with [a different translation](https://github.com/cfpb/consumerfinance.gov/blob/274b2522638ae7c2c381b632d48aa5969c54d019/cfgov/locale/es/LC_MESSAGES/django.po#L113-L114) in our parent consumerfinance.gov project ("Buscar").

This commit manually removes that translation from the Spanish django.po file. I deliberately did not run Django `makemessages` because it appears there are quite a few other translation entries that don't have code equivalents, and doing so might result in a much larger set of changes.

All unit tests continue to pass, and English and Spanish versions of the pages should still work properly.

This change addresses internal platform#3864.

### CODE REVIEW

**Comment by willbarton** [comment]
> This commit manually removes that translation from the Spanish django.po file. I deliberately did not run Django makemessages because it appears there are quite a few other translation entries that don't have code equivalents, and doing so might result in a much larger set of changes.

Is there a good place to add a note about this, that running `makemessages` in retirement could be harmful?

**Comment by Scotchester** [comment]
I'd sure like to understand how running `makemessages` in this repo could generate a translation for a string that doesn't appear in its code.

**Comment by chosak** [comment]
@Scotchester I would guess that either that string used to exist in some former version of the code OR that django.po file was previously hand-edited/hand-generated in anticipation that it might be used.

@willbarton I could add some kind of warning like that in the README, I suppose. If you run `cd retirement_api && django-admin makemessages` it generates a whole lot of changes to the file. I don't want to assess / debug all of those changes just to fix this (very visible) issue with the Spanish header, which is why I went with a manual edit. Ideally it'd be nice if this repo had similar messages checking as consumerfinance.gov does.

**Comment by willbarton** [comment]
@chosak Understandable. I can't think of a good place to put that kind of warning either — I doubt I would check the README before generating. I would probably check the previous commit message on the `.po` file, and for that, I think your commit message is sufficient for me!

**Pull request merged**
