### PR TITLE
Basic grunt task preparation

### PR DESCRIPTION
**Pull request by mistergone**
This PR is an introduction of grunt into our code. It starts with a very simple concatenation, which I'll build on in the future. This will make it easy to add automated testing into our front-end build.

I'll explain how this affects front-end development at our next stand-up, for anyone who's curious. :microscope: :octopus:

### CODE REVIEW

**Comment by marteki** [comment]
"Done, without errors."

:+1:

**Comment by niqjohnson** [comment]
:+1: 

`npm install` followed by `grunt` worked for me. Can't wait for grunt-watch + livereload!

**Comment by higs4281** [comment]
:+1: `npm install` and `grunt` ran without errors.

**Comment by mistergone** [comment]
I consider this thoroughly vetted. :octopus: :heavy_plus_sign::100:

**Pull request merged**
