### PR TITLE
Add "Claiming at" to graph message and fix associated Spanish translation

### PR DESCRIPTION
**Pull request by niqjohnson**
Add the phrase "Claiming at" to the graph message and fix the associated Spanish translation

## Changes

- The English graph message will now say something like "Claiming at age 63 reduces your monthly benefit by 25%" instead of "Age 63 reduces your monthly benefit by 25%".
- The Spanish graph message will now say something like "A los 63 años de edad, su beneficio se reducirá un 25%".

## Testing

Pull in this branch, run `python manage.py loaddata retiredata.json` and `gulp` to be safe. The big message just to the left of the graph (on desktop) should match the what's in the table below for all the cases shown there.

Your DOB | Selected claiming age | English message | Spanish message
-------- | --------------------- | --------------- | ---------------
7/7/1977 | 62–66 | Claiming at age XX **reduces** your monthly benefit by **YY**% | A los XX años de edad, su beneficio se **reducirá** un **YY**%
7/7/1977 | 67 | Age 67 is your full benefit claiming age. | 67 años de edad es su plena edad de jubilación.
7/7/1977 | 68–70 | Claiming at age XX **increases** your benefit by **YY**% | A los XX años de edad, su beneficio **aumentará** un **YY**%
1/1/1949 | 67 | Age 67 is past your full benefit claiming age. | 67 años de edad es después de haber cumplido su plena edad de jubilación.
1/1/1949 | 68–70 | Claiming at age XX **increases** your benefit by **YY**% | A los XX años de edad, su beneficio **aumentará** un **YY**%
1/1/1946 | 70 | Age 70 is your maximum benefit claiming age. | 70 años es la edad máxima para solicitar.

## Review

- @higs4281: Did I get the FRA and age 70 translation edge cases right in 			239535d? Can you find any edge cases I missed?
- @marteki 
- @mistergone 

[Preview this PR without the whitespace changes](?w=0)

## Screenshots

English (DOB 7/7/1977) | Spanish (DOB 7/7/1977)
---------------------- | ----------------------
en | es

## Notes

- Huge thanks to @higs4281 for handling all the fiddly translations!

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
:boom: can't find any bugs. tried every age that falls within the graph and ages at 1st and 2nd of month. Solid.

**Comment by marteki** [comment]
Checked all the listed cases on standalone, and all are working! :+1:

(Sorry about the conflicts to resolve. Refactoring pains. 😞 )

**Comment by mistergone** [comment]
Looks good to me, but there's conflicts to resolve.

I need this to be merged before I PR my first refactor of graph-view.js, so get to it! 😉

**Comment by niqjohnson** [comment]
@higs4281: Looks like there are some conflicts in the translation files (`retirement_api/locale/es/LC_MESSAGES/django.mo` and `retirement_api/locale/es/LC_MESSAGES/django.po`). Can I get your help resolving those when you have a chance? Thanks!

**Pull request merged**
