### PR TITLE
Add a loading indicator to improve the experience for long data retrieval times

### PR DESCRIPTION
**Pull request by marteki**
After the "Get Estimates" button is pressed, a spinning icon should appear to indicate to the user that data retrieval is occurring, and that the button click/tap was successful. It assures the user that the tool is working, and softens the uncertainty that might come from an unusually long wait time for results.

## Additions

* A `span` with an "api-data-loading-indicator" ID to the HTML file
* CSS code to hide the indicator by default, as well as to make the indicator spin
* Code in the JS to display the indicator when data retrieval begins, and hide it when it completes (or an error is received).

## Testing

- Tested in Mac Chrome and Android Chrome Beta 45.0.2454.21 with no issues.
- Tested in Safari 8.0.6. **The icon appeared and disappeared as expected, but spinning didn't occur despite `-webkit-` prefixes being included in the CSS for the animation.**

Requests for further testing in:
* iOS Safari
* iOS Chrome (if available)
* Mac Safari. Is the non-spinning replicable?
* IE 8+
* Firefox

July analytics for reference:
~36.5% IE, ~35% Chrome on some device, ~16.6% Safari (mostly on iOS), and ~7.5% Firefox.

## Review

* @mistergone
* @niqjohnson
* the original issue reporter @higs4281 

With special attention to testing in the browsers listed above, especially the IE, iOS, and Safari options.

## Screenshots

I think this deserves something better than a screenshot.

loading-indicator

## Todos

* If it's really not spinning currently in Safari, how badly it needs to spin there? Is just having the icon appear and disappear enough? Determining if it's not spinning in iOS Safari is key for me on this.

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Visually tested in supported browsers and devices 
* [ ] CHANGELOG has been updated

### CODE REVIEW

**Comment by mistergone** [comment]
It works for me, and the code looks good! :+1: :octopus:

**Comment by niqjohnson** [comment]
Looking good! Couple of things:

- I played around with it a little, and setting the display of `.cf-icon__spin` to `inline-block` instead of `inline` when it's visible gets it spinning in Safari.
- The `&nbsp;` is causing a little extra room after the words in the button when the spinner isn't showing. I think replacing the non-breaking space with some left margin on `.cf-icon__spin` should do the trick (hopefully that won't mess with the animation).

I can test again in Safari and Mobile Safari once those fixes are in to make sure everything is still working as expected.

**Comment by higs4281** [comment]
the spinner is great visual feedback for the occasional slow response. but for a good response, even a really fast one, i see a spinner flicker before the graph scroll kicks in. anyone think it's worth adding a delay, maybe 1 sec, before the spinner kicks in?

**Comment by mistergone** [comment]
@higs4281 - I'd be afraid that any delay added before the spinner appears would not really decrease the chance that it flickers (because the data comes in just after the delay). We don't have any good data right now on response times to know how long any delay like that should be...

We could make sure the spinner appears for at least, say, 750 milliseconds to avoid that "flicker" from occurring, but I don't know that that's worth the effort. Hard to say... :octopus::question:

**Comment by higs4281** [comment]
i have decent response data because i've been monitoring the api response every 5 mins from my laptop, when it's on. average response time, including the occasional long one, is .7 sec.

**Comment by marteki** [comment]
Recommended server response time according to Google is 200 ms.

From a UX standpoint, purposefully delaying showing the data in order to show the spinner instead seems... backwards. Is the flicker a strong negative?

**Comment by higs4281** [comment]
no biggie, and probably only noticeable because i'm looking for it

**Comment by niqjohnson** [comment]
:+1: Spinning for me in Safari on my laptop and iPhone 6. Button padding looks nice, too.

I can't test in IE, but [caniuse tells me animation isn't supported until IE10](http://caniuse.com/#feat=css-animation). Unless there's a fallback built in, I'm guessing that means the icon will appear in older versions of IE but not spin. Seems acceptable to me.

**Comment by marteki** [comment]
:+1:

**Pull request merged**
