### PR TITLE
Switch to standard range slider

### PR DESCRIPTION
**Pull request by niqjohnson**
Replaces the old custom slider with a standard, styled `<input type="range">` for better sliding on touch devices

## Additions

- Capital Framework `<input type="range">` styles
- IE conditionals around the opening `div.claim-canvas` to apply a `claim-canvas__no-slider` class needed to hide the new slider in browsers that don't support it (IE 9 and below)

## Removals

- HTML and JS needed to power the old custom slider

## Changes

- Standard `<input type="range">` instead of the old custom slider

## Testing

- The slider should slide on any touch or non-touch device.
- Everything else about the graph should work exactly the same way as before.
- The slider should be hidden in IE 8 and IE 9 (clicking on the graph bars or numbers should still select that age, though).
- The slider should look as it does in the screenshots below.

## Review

- @mistergone 
- @higs4281 
- @marteki 

### Large screens

Unfocused | Focused | Hidden (IE 9 and below)
-------------- | ------------ | --------------------------------
slider-fra | slider-focus | slider-ie9

### Small screens

slider-small

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
:+1: works beautifully on iphone6. bravo.

**Comment by niqjohnson** [comment]
Fixed the merge conflicts. Everything still seems to be working correctly in all browsers I tested. Whew!

**Comment by higs4281** [comment]
👍 still works great on iphone 6.

**Comment by mistergone** [comment]
Looks good to me! :+1:

**Pull request merged**
