### PR TITLE
Raphael removed, graph rewritten in HTML/CSS/JS

### PR DESCRIPTION
**Pull request by mistergone**
This PR removes Raphael from our front-end. We have no real need of SVGs to draw our graph, and simple DIVs are easier to manipulate, and probably easier to automatically test. Plus, we had some problems in IE8, and this should address those problems.

Also, holy moley, as of this PR, I have completely overhauled this codebase in three days. I did not expect to be able to do that.

## Changes
- All references to Raphael objects have been replaced with DIVs and CSS.
- Started to improve the code by making JS references to ID values or DATA properties instead of classes.

## Testing
- Pull down, run `frontendbuild.sh`, and make sure everything works!

## Review
- @marteki and @niqjohnson and @higs4281 

## Todos
- More cleanup of JS references to classes. It's better if the JS relies on IDs and DATA attributes.

## Checklist
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices 
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

## Animated GIF
it-crowd-dance

### CODE REVIEW

**Comment by marteki** [comment]
:heart_eyes: on standalone Chrome! This is fantastic! You also added `eslint` in, and linted a whole mess of stuff!

It's not an actual one-to-one match with build, but that's probably due to the CF style stuff that we're tracking from adding the new package. And I've never been one for exacting pixel-perfectness on the web anyway. If the spacing difference on the labels are a problem, they should be fixable next week.

Strong :+1: for me, who is eagerly awaiting trying this out on IE and Android.

**Comment by higs4281** [comment]
:+1: bravo
one nit, which I think has been mentioned: on later-year bars for those past FRA, I get a message \`Compared to claiming at66undefined`

**Comment by marteki** [comment]
Yeah, @higs4281, that's on me. I was waiting for the refactoring work to complete before fixing that.

**Comment by mistergone** [comment]
Okay, I see two thumbs, which is all I require. Merging!

**Pull request merged**
